"""Asterisk dialplan configuration generator."""

import logging
from typing import List, Dict, Any

logger = logging.getLogger(__name__)


class DialplanGenerator:
    """
    Generates Asterisk dialplan configuration for internal extension routing.

    Creates [synergy-internal] context with routing rules for all extensions.
    """

    @staticmethod
    def generate_config(users_with_extensions: List[Dict[str, Any]]) -> str:
        """
        Generate dialplan configuration content for all users/extensions.

        Args:
            users_with_extensions: List of user dictionaries, each containing:
                - id: User UUID
                - name: User name
                - email: User email
                - extension: Dict with number, secret, etc.

        Returns:
            String containing complete dialplan configuration in Asterisk format

        Example output:
            ; Dialplan - Auto-generated by PBX Control Portal
            ; DO NOT EDIT MANUALLY - Changes will be overwritten on next apply

            [synergy-internal]
            ; Internal extension-to-extension dialing
            exten => 1000,1,Dial(PJSIP/1000,20)
            exten => 1000,n,Hangup()

            exten => 1001,1,Dial(PJSIP/1001,20)
            exten => 1001,n,Hangup()
        """
        if not users_with_extensions:
            logger.warning("No users provided to dialplan generator, generating empty config")
            return DialplanGenerator._generate_header()

        logger.info(f"Generating dialplan config for {len(users_with_extensions)} users")

        lines = [DialplanGenerator._generate_header()]
        lines.append("[synergy-internal]")
        lines.append("; Internal extension-to-extension dialing")

        for user in users_with_extensions:
            extension = user.get("extension")
            if not extension:
                logger.warning(f"User {user.get('id')} has no extension, skipping dialplan")
                continue

            extension_number = extension.get("number")

            if not extension_number:
                logger.warning(f"User {user.get('id')} missing extension number, skipping")
                continue

            # Generate dial pattern for this extension
            lines.append(DialplanGenerator._generate_extension_dial(extension_number))
            lines.append("")  # Blank line between extensions

        config = "\n".join(lines)
        logger.info(f"Dialplan config generated: {len(lines)} lines")
        return config

    @staticmethod
    def _generate_header() -> str:
        """Generate configuration file header with warnings."""
        return """; Dialplan - Auto-generated by PBX Control Portal
; DO NOT EDIT MANUALLY - Changes will be overwritten on next apply
; Generated extensions are in range 1000-1999
;
; Context: synergy-internal
;   Used for extension-to-extension dialing within the organization
"""

    @staticmethod
    def _generate_extension_dial(extension_number: int) -> str:
        """
        Generate dialplan extension block for an extension.

        Creates a simple Dial() application with 20 second timeout.

        Args:
            extension_number: Extension number (1000-1999)

        Returns:
            Dialplan configuration lines for this extension
        """
        return f"""exten => {extension_number},1,Dial(PJSIP/{extension_number},20)
exten => {extension_number},n,Hangup()"""
